development:
  shopify_api_key: "c67c6718da87efdf792547a6bb83a3c7"
  shopify_secret: "046a6fc5252d1d85602eea6d1aac558f"
  ups_user_id: 'jnatowitz@lapineinc.com'
  ups_password: 'P444word!'
  ups_key: 'ACD8A71E16D5BA35'
  app_url: 'http://localhost:3000'
  pre_fix_url: ''
production:
  shopify_api_key: "f510bde1a4ee22623532723cf74a60f6"
  shopify_secret: "89c26e88dba118d778c1ff8435f99069"
  ups_user_id: 'jnatowitz@lapineinc.com'
  ups_password: 'P444word!'
  ups_key: 'ACD8A71E16D5BA35'
  app_url: 'http://shopify-bulk-order.herokuapp.com'
  pre_fix_url: '/apps'